---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: llama-stack
placementBindingDefaults:
  name: llama-stack
policyDefaults:
  placement:
    placementName: placement-hub-openshift
  categories:
    - CM Configuration Management
  complianceType: "musthave"
  controls:
    - CM-2 Baseline Configuration
  consolidateManifests: false
  copyPolicyMetadata: false
  disabled: false
  namespace: openshift-policy
  pruneObjectBehavior: "None"
  remediationAction: enforce
  recreateOption: IfRequired
  severity: medium
  tool_groups:
    - toolgroup_id: mcp::github
      provider_id: model-context-protocol
      mcp_endpoint:
        uri: http://github-mcp-server.agent-demo.svc.cluster.local:80/sse
  tool_runtime:
      - provider_id: model-context-protocol
        provider_type: remote::model-context-protocol
        config: {}
  standards:
    - NIST SP 800-53
  policyAnnotations: {"argocd.argoproj.io/compare-options": "IgnoreExtraneous",
                      "avp.kubernetes.io/path": "kv/data/ocp/sno/openshift-policy/llama-stack"}
policies:
  - name: llama-stack-sno
    manifests:
      - path: mcp-github/
